server.port=8080

# Development Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/employee-performance-tracker
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA & Hibernate Settings
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format-sql=true

# Logging levels (Detailed for development)
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

# Flyway Migration
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
